[package]
name = "ocean"
version = "0.1.0"
edition = "2021"
exclude = ["./ocean-language-support/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ocean_helpers = { path = "ocean_helpers" }
regex = "1.9.3"
rustyline = "12.0.0"
